apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-env-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-env-demo
  template:
    metadata:
      labels:
        app: nginx-env-demo
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          env:
            - name: APP_MODE
              value: "production"
            - name: WELCOME_MSG
              value: "Hello from Kubernetes"
