apiVersion: v1
kind: Pod
metadata:
  name: nginx-env-demo
spec:
  containers:
    - name: nginx
      image: nginx:latest
      env:
        - name: APP_MODE
          value: "production"
        - name: WELCOME_MSG
          value: "Hello from Kubernetes"
